openapi: 3.0.3
############################################################################
#                                     API info                             #
############################################################################
info:
  title: Call Forwarding Signal API
  version: 0.1.0
  description: |
    ## Overview
    TBD 
    
    ## 1. Introduction
    TBD    
    
    ## 2. Quick Start
    TBD
    
    Before starting to use the TI API, the developer needs to know about the below specified details:
   
    **Base-Url**
    The RESTful CFS API endpoint, for example [**https://tim-api.developer.tim.it/callforwardingsignal**](https://tim-api.developer.tim.it/callforwardingsignal)
   
    **Authentication**
    Configure security access keys such as OAuth 2.0 client credentials to be used by Client applications which will invoke the CFS API.
   
    **phoneNumber**
    This is the end user phone number. THe CFS API verifyes if a call forwarding service is active on this phone number
  
    ## 3. Authentication and Authorization
    The CFS API makes use of the client credentials grant which is applicable for server to server use cases involving trusted partners or clients without any protected user data involved.
    In this method the CFS API invoker client is registered as a confidential client with an authorization grant type of client\_credentials.
    
    ## 4. API Documentation
    ## 4.1 Details
    
    TBD
    
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

externalDocs:
  description: Product documentation at Camara
  url: https://github.com/camaraproject/CallForwardingSignal
  
  
############################################################################
#                                     Security                             #
############################################################################
security:
  - oAuth2:
      - 'call-forwarding:call-forwardings:read'

############################################################################
#                                     Servers                              #
############################################################################
servers:
  - url: "{apiRoot}/{basePath}"
    variables:
      apiRoot:
        default: http://localhost:9091
        description: API root
      basePath:
        default: cfs/v0
        description: Base path for the Call Forwarding Signal API



############################################################################
#                                     Paths                                #
############################################################################
paths:
  /subscribers/{subscriberId}/call-forwardings:
    get:
      parameters:
        - in: path 
          name: subscriberId
          schema:
            $ref: "#/components/schemas/PhoneNumber"
          description: phone number on which checking if a call forwarding service is active
          required: true
      tags:
        - Call Forwarding API GET Operation
      summary: provides the information if a call forwarding service is active on the provided phone number (phoneNumber)
      operationId: getCallForwarding
      responses:
        '200':
          description: OK. 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CallForwardings'
        '404':
          $ref: '#/components/responses/ResNotFound'
        '500':
          $ref: '#/components/responses/GenericError'
        '504':
          $ref: '#/components/responses/BackendConnTimeout'
        "401":
          $ref: "#/components/responses/Generic401"
        "403":
          $ref: "#/components/responses/Generic403"
        "503":
          $ref: "#/components/responses/Generic503"

components:
  securitySchemes:
    oAuth2:    
      type: oauth2
      description: This API uses OAuth 2 [More info](https://api.example.com/docs/auth)
      flows:        
        clientCredentials:
          tokenUrl: 'https://example.com/oauth/token'
          scopes:
            'call-forwarding:call-forwardings:read': Grant read-only call-forwardings data


 #######################################################
 #  RESOURCES
 #######################################################
  
  schemas:

    CallForwardings:
      type: object
      properties:
        active:
          type: boolean
          description: Indicates if a call forwarding service is active.


 #######################################################
 #  TYPES
 #######################################################    

    PhoneNumber:
     description: A public identifier addressing a telephone subscription. In mobile networks it corresponds to the MSISDN (Mobile Station International Subscriber Directory Number). In order to be globally unique it has to be formatted in international format, according to E.164 standard, prefixed with '+'.
     type: string
     pattern: '^\+[1-9][0-9]{4,14}$'
     example: "+123456789"
    
    

 ######################################################
 #  RESPONSES
 #######################################################            
    ErrResponse:
      type: object
      properties:
        status:
          type: string
          example: OK
        message:
          type: string
          example: OK
    ErrorInfo:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          description: Code given to this error
        message:
          type: string
          description: Detailed error description
  responses:
    ResNotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrResponse'
          example:
            status: ERROR
            message: Resource not found
    GenericError:
      description: An unknow error has occurred
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrResponse'
          example:
            status: ERROR
            message: Generic error
    BackendConnTimeout:
      description: Connection timeout towards backend service has occurred
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrResponse'
          example:
            status: ERROR
            message: Backend connection timeout
    OkDeletionInProgress:
      description: The resource delation request has been accepted
      content:
        application/json:
          example:
            status: OK
            message: Accepted
    Generic400:
      description: Invalid input
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorInfo"
          example:
            code: INVALID_INPUT
            message: "Schema validation failed at  ..."
    Generic401:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorInfo"
          example:
            code: UNAUTHORIZED
            message: "Authorization failed: ..."
    Generic403:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorInfo"
          example:
            code: FORBIDDEN
            message: "Operation not allowed: ..."
    SessionNotFound404:
      description: Session not found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorInfo"
          example:
            code: NOT_FOUND
            message: "Session Id does not exist"
    Generic503:
      description: Service unavailable
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorInfo"
          example:
            code: SERVICE_UNAVALIBLE
            message: "Service unavailable" 