openapi: 3.0.3
############################################################################
#                                     API info                             #
############################################################################
info:
  title: Call Forwarding Signal API
  version: 0.1.0
  description: |
    ## Overview
    TBD 
    
    ## 1. Introduction
    TBD    
    
    ## 2. Quick Start
    TBD
    
    Before starting to use the Call Forwarding API, the developer needs to know about the below specified details:
   
    **Base-Url**
    The RESTful CFS API endpoint, for example [**https://tim-api.developer.tim.it/callforwardingsignal**](https://tim-api.developer.tim.it/callforwardingsignal)
   
   
    **phoneNumber**
    This is the end user phone number. The CFS API verifies if a call forwarding service is active on this phone number.
  
    ## Authorization and authentication

    CAMARA guidelines defines a set of authorization flows which can grant API clients access to the API functionality, 
    as outlined in the document [CAMARA-API-access-and-user-consent.md](https://github.com/camaraproject/IdentityAndConsentManagement/blob/main/documentation/CAMARA-API-access-and-user-consent.md). 
    Which specific authorization flows are to be used will be determined during onboarding process, happening between the API Client and the 
    Telco Operator exposing the API, taking into account the declared purpose for accessing the API, while also being subject to the prevailing legal 
    framework dictated by local legislation.

    It is important to remark that in cases where personal user data is processed by the API, and users can exercise their rights through mechanisms suc
     as opt-in and/or opt-out, the use of 3-legged access tokens becomes mandatory. 
     This measure ensures that the API remains in strict compliance with user privacy preferences and regulatory obligations, 
     upholding the principles of transparency and user-centric data control.
    
    ## 4. API Documentation
    ## 4.1 Details
    
    TBD
    
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

externalDocs:
  description: Product documentation at Camara
  url: https://github.com/camaraproject/CallForwardingSignal
  


############################################################################
#                                     Servers                              #
############################################################################
servers:
  - url: "{apiRoot}/{basePath}"
    variables:
      apiRoot:
        default: http://localhost:9091
        description: API root
      basePath:
        default: cfs/v0
        description: Base path for the Call Forwarding Signal API



############################################################################
#                                     Paths                                #
############################################################################
paths:
  /call-forwardings:
    post:
      tags:
        - Call Forwarding information retrieval
      security:
        - openId:
          - call-forwarding:read
      description: Retrieve the information about call forwarding service active on a phone number     
      operationId: retriveCallForwarding
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PhoneNumber'
        required: true
      responses:
        '200':
          description: OK. 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CallForwardings'
        '404':
          $ref: '#/components/responses/ResNotFound'
        '500':
          $ref: '#/components/responses/GenericError'
        '504':
          $ref: '#/components/responses/BackendConnTimeout'
        "401":
          $ref: "#/components/responses/Generic401"
        "403":
          $ref: "#/components/responses/Generic403"
        "503":
          $ref: "#/components/responses/Generic503"

components:
  securitySchemes:
    openId:
      type: openIdConnect
      openIdConnectUrl: https://example.com/.well-known/openid-configuration


 #######################################################
 #  RESOURCES
 #######################################################
  
  schemas:

    CallForwardings:
      type: object
      properties:
        active:
          type: boolean
          description: Indicates if a call forwarding service is active.


 #######################################################
 #  TYPES
 #######################################################    

    PhoneNumber:
     description: A public identifier addressing a telephone subscription. In mobile networks it corresponds to the MSISDN (Mobile Station International Subscriber Directory Number). In order to be globally unique it has to be formatted in international format, according to E.164 standard, prefixed with '+'.
     type: string
     pattern: '^\+[1-9][0-9]{4,14}$'
     example: "+123456789"
    
    

 ######################################################
 #  RESPONSES
 #######################################################            
    ErrResponse:
      type: object
      properties:
        status:
          type: string
          example: OK
        message:
          type: string
          example: OK
    ErrorInfo:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          description: Code given to this error
        message:
          type: string
          description: Detailed error description
  responses:
    ResNotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrResponse'
          example:
            status: ERROR
            message: Resource not found
    GenericError:
      description: An unknow error has occurred
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrResponse'
          example:
            status: ERROR
            message: Generic error
    BackendConnTimeout:
      description: Connection timeout towards backend service has occurred
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrResponse'
          example:
            status: ERROR
            message: Backend connection timeout
    OkDeletionInProgress:
      description: The resource delation request has been accepted
      content:
        application/json:
          example:
            status: OK
            message: Accepted
    Generic400:
      description: Invalid input
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorInfo"
          example:
            code: INVALID_INPUT
            message: "Schema validation failed at  ..."
    Generic401:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorInfo"
          example:
            code: UNAUTHORIZED
            message: "Authorization failed: ..."
    Generic403:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorInfo"
          example:
            code: FORBIDDEN
            message: "Operation not allowed: ..."
    SessionNotFound404:
      description: Session not found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorInfo"
          example:
            code: NOT_FOUND
            message: "Session Id does not exist"
    Generic503:
      description: Service unavailable
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorInfo"
          example:
            code: SERVICE_UNAVALIBLE
            message: "Service unavailable" 